export const homeObjThree = {
  id: "gallery",
  lightBg: false,
  lightText: true,
  lightDescription: true,
  topLine: "gallery",
  headline: "Capture Every Beautiful Moment of Life",
  descriptionp1:
    "I LOVE SPEDING TIME ON CAPTURING EVERY BEAUTIFUL MOMENT OF LIFE.",
  descriptionp2: "💜 I just begin to learn paintings.",
  descriptionp3: "💛 I have two pets: a bunny and a dachshund - sausage dog.",
  descriptionp4: "💚 And I am good at planting avocados",
  buttonLabel: "Checkout my works",
  imgStart: true,
  img: require("../../images/gallery.png"),
  alt: "Mengyi's gallery",
  dark: true,
  primary: true,
  darkText: false,
};
